# coding: utf-8

"""
    GameBrain API

    GameBrain API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gamebrain.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_detail(self) -> None:
        """Test case for detail

        GET v1/games/{id}
        """
        pass

    def test_search(self) -> None:
        """Test case for search

        GET v1/games
        """
        pass

    def test_similar(self) -> None:
        """Test case for similar

        GET v1/games/{id}/similar
        """
        pass

    def test_suggest(self) -> None:
        """Test case for suggest

        GET v1/games/suggestions
        """
        pass


if __name__ == '__main__':
    unittest.main()
