{-
   GameBrain API

   GameBrain API

   OpenAPI Version: 3.0.3
   GameBrain API API version: 1.0.0
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : GameBrain.API.ApiDefault
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module GameBrain.API.ApiDefault where

import GameBrain.Core
import GameBrain.MimeTypes
import GameBrain.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Default

-- *** detail

-- | @GET \/games\/{id}@
-- 
-- GET v1/games/{id}
-- 
detail
  :: Id -- ^ "id"
  -> ApiKey -- ^ "apiKey"
  -> GameBrainRequest Detail MimeNoContent GameResponse MimeJSON
detail (Id id) (ApiKey apiKey) =
  _mkRequest "GET" ["/games/",toPath id]
    `addQuery` toQuery ("api-key", Just apiKey)

data Detail  
-- | @application/json@
instance Produces Detail MimeJSON


-- *** search

-- | @GET \/games@
-- 
-- GET v1/games
-- 
search
  :: Query -- ^ "query"
  -> Offset -- ^ "offset"
  -> Limit -- ^ "limit"
  -> Filters -- ^ "filters"
  -> Sort -- ^ "sort"
  -> SortOrder -- ^ "sortOrder"
  -> GenerateFilterOptions -- ^ "generateFilterOptions"
  -> ApiKey -- ^ "apiKey"
  -> GameBrainRequest Search MimeNoContent SearchResponse MimeJSON
search (Query query) (Offset offset) (Limit limit) (Filters filters) (Sort sort) (SortOrder sortOrder) (GenerateFilterOptions generateFilterOptions) (ApiKey apiKey) =
  _mkRequest "GET" ["/games"]
    `addQuery` toQuery ("query", Just query)
    `addQuery` toQuery ("offset", Just offset)
    `addQuery` toQuery ("limit", Just limit)
    `addQuery` toQuery ("filters", Just filters)
    `addQuery` toQuery ("sort", Just sort)
    `addQuery` toQuery ("sort-order", Just sortOrder)
    `addQuery` toQuery ("generate-filter-options", Just generateFilterOptions)
    `addQuery` toQuery ("api-key", Just apiKey)

data Search  
-- | @application/json@
instance Produces Search MimeJSON


-- *** similar

-- | @GET \/games\/{id}\/similar@
-- 
-- GET v1/games/{id}/similar
-- 
similar
  :: Id -- ^ "id"
  -> Limit -- ^ "limit"
  -> ApiKey -- ^ "apiKey"
  -> GameBrainRequest Similar MimeNoContent SimilarGamesResponse MimeJSON
similar (Id id) (Limit limit) (ApiKey apiKey) =
  _mkRequest "GET" ["/games/",toPath id,"/similar"]
    `addQuery` toQuery ("limit", Just limit)
    `addQuery` toQuery ("api-key", Just apiKey)

data Similar  
-- | @application/json@
instance Produces Similar MimeJSON


-- *** suggest

-- | @GET \/games\/suggestions@
-- 
-- GET v1/games/suggestions
-- 
suggest
  :: Query -- ^ "query"
  -> Limit -- ^ "limit"
  -> ApiKey -- ^ "apiKey"
  -> GameBrainRequest Suggest MimeNoContent SearchSuggestionResponse MimeJSON
suggest (Query query) (Limit limit) (ApiKey apiKey) =
  _mkRequest "GET" ["/games/suggestions"]
    `addQuery` toQuery ("query", Just query)
    `addQuery` toQuery ("limit", Just limit)
    `addQuery` toQuery ("api-key", Just apiKey)

data Suggest  
-- | @application/json@
instance Produces Suggest MimeJSON

