{-
   GameBrain API
   GameBrain API

   The version of the OpenAPI document: 1.0.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Default exposing
    ( detail
    , search
    , similar
    , suggest
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode

detail : Int -> String -> Api.Request Api.Data.GameResponse
detail id_path apiKey_query =
    Api.request
        "GET"
        "/games/{id}"
        [ ( "id", String.fromInt id_path ) ]
        [ ( "api-key", Just <| identity apiKey_query ) ]
        []
        Nothing
        Api.Data.gameResponseDecoder


search : String -> Int -> Int -> String -> String -> String -> Bool -> String -> Api.Request Api.Data.SearchResponse
search query_query offset_query limit_query filters_query sort_query sortOrder_query generateFilterOptions_query apiKey_query =
    Api.request
        "GET"
        "/games"
        []
        [ ( "query", Just <| identity query_query ), ( "offset", Just <| String.fromInt offset_query ), ( "limit", Just <| String.fromInt limit_query ), ( "filters", Just <| identity filters_query ), ( "sort", Just <| identity sort_query ), ( "sort-order", Just <| identity sortOrder_query ), ( "generate-filter-options", Just <| (\val -> if val then "true" else "false") generateFilterOptions_query ), ( "api-key", Just <| identity apiKey_query ) ]
        []
        Nothing
        Api.Data.searchResponseDecoder


similar : Int -> Int -> String -> Api.Request Api.Data.SimilarGamesResponse
similar id_path limit_query apiKey_query =
    Api.request
        "GET"
        "/games/{id}/similar"
        [ ( "id", String.fromInt id_path ) ]
        [ ( "limit", Just <| String.fromInt limit_query ), ( "api-key", Just <| identity apiKey_query ) ]
        []
        Nothing
        Api.Data.similarGamesResponseDecoder


suggest : String -> Int -> String -> Api.Request Api.Data.SearchSuggestionResponse
suggest query_query limit_query apiKey_query =
    Api.request
        "GET"
        "/games/suggestions"
        []
        [ ( "query", Just <| identity query_query ), ( "limit", Just <| String.fromInt limit_query ), ( "api-key", Just <| identity apiKey_query ) ]
        []
        Nothing
        Api.Data.searchSuggestionResponseDecoder

