{-
   GameBrain API

   GameBrain API

   OpenAPI Version: 3.0.3
   GameBrain API API version: 1.0.0
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : GameBrain.Logging
Logging functions
-}
{-# LANGUAGE CPP #-}

#ifdef USE_KATIP

module GameBrain.Logging
  ( module GameBrain.LoggingKatip
  ) where

import GameBrain.LoggingKatip

#else

module GameBrain.Logging
  ( module GameBrain.LoggingMonadLogger
  ) where

import GameBrain.LoggingMonadLogger

#endif
