/*
 * GameBrain API
 * GameBrain API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package co.gamebrain;

import co.gamebrain.client.ApiException;
import co.gamebrain.client.model.GameResponse;
import co.gamebrain.client.model.SearchResponse;
import co.gamebrain.client.model.SearchSuggestionResponse;
import co.gamebrain.client.model.SimilarGamesResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Disabled
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * GET v1/games/{id}
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void detailTest() throws ApiException {
        Integer id = null;
        String apiKey = null;
        GameResponse response = api.detail(id, apiKey);
        // TODO: test validations
    }

    /**
     * GET v1/games
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void searchTest() throws ApiException {
        String query = null;
        Integer offset = null;
        Integer limit = null;
        String filters = null;
        String sort = null;
        String sortOrder = null;
        Boolean generateFilterOptions = null;
        String apiKey = null;
        SearchResponse response = api.search(query, offset, limit, filters, sort, sortOrder, generateFilterOptions, apiKey);
        // TODO: test validations
    }

    /**
     * GET v1/games/{id}/similar
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void similarTest() throws ApiException {
        Integer id = null;
        Integer limit = null;
        String apiKey = null;
        SimilarGamesResponse response = api.similar(id, limit, apiKey);
        // TODO: test validations
    }

    /**
     * GET v1/games/suggestions
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void suggestTest() throws ApiException {
        String query = null;
        Integer limit = null;
        String apiKey = null;
        SearchSuggestionResponse response = api.suggest(query, limit, apiKey);
        // TODO: test validations
    }

}
