/**
 * GameBrain API
 * GameBrain API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GameResponsePlaytime { 
    percentiles?: Array<number>;
    min?: number;
    median?: number;
    max?: number;
    mean?: number;
    mentions?: number;
}

