/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package co.gamebrain

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import co.gamebrain.DefaultApi
import co.gamebrain.client.model.GameResponse
import co.gamebrain.client.model.SearchResponse
import co.gamebrain.client.model.SearchSuggestionResponse
import co.gamebrain.client.model.SimilarGamesResponse

class DefaultApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DefaultApi
        //val apiInstance = DefaultApi()

        // to test detail
        should("test detail") {
            // uncomment below to test detail
            //val id : kotlin.Int = 56 // kotlin.Int | 
            //val apiKey : kotlin.String = apiKey_example // kotlin.String | 
            //val result : GameResponse = apiInstance.detail(id, apiKey)
            //result shouldBe ("TODO")
        }

        // to test search
        should("test search") {
            // uncomment below to test search
            //val query : kotlin.String = query_example // kotlin.String | 
            //val offset : kotlin.Int = 56 // kotlin.Int | 
            //val limit : kotlin.Int = 56 // kotlin.Int | 
            //val filters : kotlin.String = filters_example // kotlin.String | 
            //val sort : kotlin.String = sort_example // kotlin.String | 
            //val sortOrder : kotlin.String = sortOrder_example // kotlin.String | 
            //val generateFilterOptions : kotlin.Boolean = true // kotlin.Boolean | 
            //val apiKey : kotlin.String = apiKey_example // kotlin.String | 
            //val result : SearchResponse = apiInstance.search(query, offset, limit, filters, sort, sortOrder, generateFilterOptions, apiKey)
            //result shouldBe ("TODO")
        }

        // to test similar
        should("test similar") {
            // uncomment below to test similar
            //val id : kotlin.Int = 56 // kotlin.Int | 
            //val limit : kotlin.Int = 56 // kotlin.Int | 
            //val apiKey : kotlin.String = apiKey_example // kotlin.String | 
            //val result : SimilarGamesResponse = apiInstance.similar(id, limit, apiKey)
            //result shouldBe ("TODO")
        }

        // to test suggest
        should("test suggest") {
            // uncomment below to test suggest
            //val query : kotlin.String = query_example // kotlin.String | 
            //val limit : kotlin.Int = 56 // kotlin.Int | 
            //val apiKey : kotlin.String = apiKey_example // kotlin.String | 
            //val result : SearchSuggestionResponse = apiInstance.suggest(query, limit, apiKey)
            //result shouldBe ("TODO")
        }

    }
}
