=begin
#GameBrain API

#GameBrain API

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.8.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::DefaultApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::DefaultApi)
    end
  end

  # unit tests for detail
  # GET v1/games/{id}
  # @param id 
  # @param api_key 
  # @param [Hash] opts the optional parameters
  # @return [GameResponse]
  describe 'detail test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for search
  # GET v1/games
  # @param query 
  # @param offset 
  # @param limit 
  # @param filters 
  # @param sort 
  # @param sort_order 
  # @param generate_filter_options 
  # @param api_key 
  # @param [Hash] opts the optional parameters
  # @return [SearchResponse]
  describe 'search test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for similar
  # GET v1/games/{id}/similar
  # @param id 
  # @param limit 
  # @param api_key 
  # @param [Hash] opts the optional parameters
  # @return [SimilarGamesResponse]
  describe 'similar test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for suggest
  # GET v1/games/suggestions
  # @param query 
  # @param limit 
  # @param api_key 
  # @param [Hash] opts the optional parameters
  # @return [SearchSuggestionResponse]
  describe 'suggest test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
